### ISSUE TITLE
Int ./. Float

### ISSUE THREAD

**Issue by sjanssen2** [mortonjt/ancomP#1]
Hi Jamie,
I saw that results of ancomp differ with regards of the data type of the count array. If I provide the very same numbers as floats, results seems to be reasonable. If I am using Integers way too much features are rejected. Could it be a problem of the division by the sum of all counts, resulting in either 0 or 1 in the integer case?
If yes, is this a bug or a feature?

**Comment by jwdebelius** [comment]
When I use `closure` from scikit-bio, I get identical matrices:

```
>>> genus_norm = pd.DataFrame(closure(genus + 1), index=genus.index, columns=genus.columns)
>>> genus_check = pd.DataFrame(closure(genus + 1.0), index=genus.index, columns=genus.columns)
>>> (genus_norm.index == genus_check.index).all()
True
>>> (genus_norm.columns == genus_check.columns).all()
True
>>> (genus_norm.values == genus_check.values).all()
True 
```

**Comment by mortonjt** [comment]
@sjanssen2 , @jwdebelius that sounds like a bug.  Can you provide some examples so that I can replicate this issue?

**Comment by wasade** [comment]
I believe this is the issue I was noticing before where like everything was
being rejected. I think this should be considered critical

cc @gregcaporaso

**Comment by gregcaporaso** [comment]
Should this issue be moved to scikit-bio? I'm unsure of the relationship between the code in this repo and the code in scikit-bio.

**Comment by mortonjt** [comment]
Let's hold off of that for a sec. I _think_ that the issues are stemming
from the permutation testing.

**Comment by mortonjt** [comment]
The bug came from an accidental rounding error.  Thank @sjanssen2 for catching it!

**Comment by gregcaporaso** [comment]
Is this a bug in the scikit-bio implementation?

**Comment by mortonjt** [comment]
Nope :)

**Comment by gregcaporaso** [comment]
Ok, thanks!

**Comment by wasade** [comment]
Really? This bug sounds really similar to an issue I've been having (but
haven't been able to isolate) with skbio's implementation

**Comment by mortonjt** [comment]
Yeah.  There is no difference between ints and floats in the scikit-bio ancom.  There was some weird casting in the permutative test that was not right.

If you are seeing other weird issues, let's talk.  And we can discuss how to diagnose it.
